name: Wen-Yen Chang
# url: http://bamos.github.io
# url: http://github.com/Jwy-Leo/
# url: http://wenyen.github.io
url: http://jwy-leo.github.io
# url: Jwy-Leo.github.io
# baseurl: wenyen.github.io
destination: ./_site
twitter: brandondamos
lsi: false
port: 4000
markdown: kramdown
future: true
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
permalink: pretty
#paginate: 5
gems:
  - jekyll-sitemap

exclude:
  - .travis.yml
  - validate.rb
  - README.md
  - Gemfile
  - Gemfile.lock
  - bower_components
  - update-vendor-deps.sh
  - vendor/bundle
  - vendor/bower.json
